spring:
  datasource:
    username: admin
    password: admin
    url: jdbc:postgresql://localhost:5432/shop
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop